// export const FETCH_IMAGES_STARTED = 'GET_USER_LIST';
// export const FETCH_IMAGES_SUCCESS = 'GET_USER_LIST';
// export const FETCH_IMAGES_FAIL = 'GET_USER_LIST';

export const FETCH_IMAGES_STARTED = 'FETCH_IMAGES_STARTED';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAIL = 'FETCH_IMAGES_FAIL';

export const BEFORE_FETCH_START = 'BEFORE_FETCH_START';
export const AFTER_FETCH_COMPLETE = 'AFTER_FETCH_COMPLETE';
// export const FETCH_IMAGES_FAIL = 'GET_USER_LIST';

