// export const FETCH_IMAGES_STARTED = 'GET_USER_LIST';
// export const FETCH_IMAGES_SUCCESS = 'GET_USER_LIST';
// export const FETCH_IMAGES_FAIL = 'GET_USER_LIST';

export const FETCH_IMAGES_STARTED = 'FETCH_IMAGES_STARTED';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAIL = 'FETCH_IMAGES_FAIL';

// export const FETCH_IMAGES_STARTED = 'GET_USER_LIST';
// export const FETCH_IMAGES_SUCCESS = 'GET_USER_LIST';
// export const FETCH_IMAGES_FAIL = 'GET_USER_LIST';

